export const Citylist = [
    {
        state: "Rajasthan",
        cities: [
            "Other",
            "Ajmer", 
            "Alwar", 
            "Banswara", 
            "Baran", 
            "Barmer", 
            "Bharatpur", 
            "Bhilwara", 
            "Bikaner", 
            "Bundi", 
            "Chittorgarh", 
            "Churu", 
            "Dausa", 
            "Dholpur", 
            "Dungarpur", 
            "Hanumangarh", 
            "Jaipur", 
            "Jaisalmer", 
            "Jalore", 
            "Jhalawar", 
            "Jhunjhunu", 
            "Jodhpur", 
            "Karauli", 
            "Kota", 
            "Nagaur", 
            "Pali", 
            "Pratapgarh", 
            "Rajsamand", 
            "Sawai Madhopur", 
            "Sikar", 
            "Sirohi", 
            "Sri Ganganagar", 
            "Tonk", 
            "Udaipur"
        ]
    }
];
