export const Locationlist = [
    {
        location: [
            "Vaishali Nagar Jaipur, Rajasthan ",
            "Lalarpura Jaipur, Rajasthan ",
            "Malviya Nagar Jaipur, Rajasthan ",
            "C-Scheme Jaipur, Rajasthan ",
            "Bani Park Jaipur, Rajasthan ",
            "Sindhi Camp Jaipur, Rajasthan ",
            "Jhotwara Jaipur, Rajasthan ",
            "Sanganer Jaipur, Rajasthan ",
            "Amer Fort Jaipur, Rajasthan ",
            "Hawa Mahal Jaipur, Rajasthan ",
            "Jaipur City Jaipur, Rajasthan ",
            "Vidhyadhar Nagar Jaipur, Rajasthan ",
            "Ajmer Road Jaipur, Rajasthan ",
            "Tonk Road Jaipur, Rajasthan ",
            "Mansarovar Jaipur, Rajasthan ",
            "Shastri Nagar Jaipur, Rajasthan ",
            "Rajendra Nagar Jaipur, Rajasthan ",
            "Ganpati Plaza Jaipur, Rajasthan ",
            "Chandpole Jaipur, Rajasthan ",
            "Chokhi Dhani Jaipur, Rajasthan ",
            "Khatipura Jaipur, Rajasthan ",
            "Bagru Jaipur, Rajasthan ",
            "Sawai Jai Singh Pura Jaipur, Rajasthan ",
            "Sikar Road Jaipur, Rajasthan ",
            "Raja Park Jaipur, Rajasthan ",
            "Narain Singh Circle Jaipur, Rajasthan ",
            "Pratap Nagar Jaipur, Rajasthan ",
            "Govind Marg Jaipur, Rajasthan ",
            "Shyamnagar Jaipur, Rajasthan ",
            "Bais Godown Jaipur, Rajasthan ",
            "Nehru Place Jaipur, Rajasthan ",
            "Pahar Ganj Jaipur, Rajasthan ",
            "Kota Road Jaipur, Rajasthan ",
            "Manasarovar Extension Jaipur, Rajasthan ",
            "Vidyadhar Nagar Extension Jaipur, Rajasthan ",
            "Moti Dungri Jaipur, Rajasthan ",
            "Tonk Phatak Jaipur, Rajasthan ",
            "Sanganer Airport Jaipur, Rajasthan ",
            "Brahmpuri Jaipur, Rajasthan ",
            "Durgapura Jaipur, Rajasthan ",
            "Sanganer Village Jaipur, Rajasthan ",
            "Gopalpura Bypass Jaipur, Rajasthan ",
            "Bais Godown Extension Jaipur, Rajasthan ",
            "Kanti Nagar Jaipur, Rajasthan ",
            "Jawahar Nagar Jaipur, Rajasthan ",
            "Ajmer Road Extension Jaipur, Rajasthan ",
            "Mansarovar Industrial Area Jaipur, Rajasthan ",
            "Vidhyadhar Nagar Market Jaipur, Rajasthan ",
            "Jhalana Doongri Jaipur, Rajasthan ",
            "Sukhdev Nagar Jaipur, Rajasthan ",
            "Govindgarh Jaipur, Rajasthan ",
            "Bikanervala Jaipur, Rajasthan ",
            "Shahpura Jaipur, Rajasthan ",
            "C-Scheme Market Jaipur, Rajasthan ",
            "Kishanpole Bazaar Jaipur, Rajasthan ",
            "Choti Chaupar Jaipur, Rajasthan ",
            "Pani Pech Jaipur, Rajasthan ",
            "Bapu Nagar Jaipur, Rajasthan ",
            "Rani Sati Dadi Mandir Jaipur, Rajasthan ",
            "Sanganer Market Jaipur, Rajasthan ",
            "Chandrashekar Azad Nagar Jaipur, Rajasthan ",
            "Shyam Nagar Jaipur, Rajasthan ",
            "Rajasthan University Jaipur, Rajasthan ",
            "Vaishali Circle Jaipur, Rajasthan ",
            "Raja Park Extension Jaipur, Rajasthan ",
            "Rani Bagh Jaipur, Rajasthan ",
            "Ashok Nagar Jaipur, Rajasthan ",
            "Bhagwati Nagar Jaipur, Rajasthan ",
            "Sanganer Thana Jaipur, Rajasthan ",
            "Jeevan Vihar Jaipur, Rajasthan ",
            "Krishna Nagar Jaipur, Rajasthan ",
            "Brahmpuri Extension Jaipur, Rajasthan ",
            "Shree Ram Nagar Jaipur, Rajasthan ",
            "Sanganer Tehsil Jaipur, Rajasthan ",
            "Patanjali Chikitsalaya Jaipur, Rajasthan ",
            "Jagatpura Jaipur, Rajasthan ",
            "Sardar Patel Marg Jaipur, Rajasthan ",
            "Mansarovar Park Jaipur, Rajasthan ",
            "Nehru Nagar Jaipur, Rajasthan ",
            "Kalyanji Ka Mandir Jaipur, Rajasthan ",
            "Kishanpole Jaipur, Rajasthan ",
            "Ramesh Nagar Jaipur, Rajasthan ",
            "Bhanpur Jaipur, Rajasthan ",
            "Haldiyon Ka Rasta Jaipur, Rajasthan ",
            "Rajasthan State Sports Council Jaipur, Rajasthan ",
            "Sanjay Nagar Jaipur, Rajasthan ",
            "Shastri Circle Jaipur, Rajasthan ",
            "Ajmer Road Flyover Jaipur, Rajasthan ",
            "Mangal Marg Jaipur, Rajasthan ",
            "Surajpole Jaipur, Rajasthan ",
            "Bhagwan Das Road Jaipur, Rajasthan ",
            "Kalyanji Ka Rasta Jaipur, Rajasthan ",
            "Ganga Jamuna Jaipur, Rajasthan ",
            "Bapu Bazar Jaipur, Rajasthan ",
            "Nehru Garden Jaipur, Rajasthan ",
            "Sikar Road Extension Jaipur, Rajasthan ",
            "Chandrawal Jaipur, Rajasthan ",
            "Mahatma Gandhi Road Jaipur, Rajasthan ",
            "Ramganj Jaipur, Rajasthan ",
            "Khandelwal Sweets Jaipur, Rajasthan"
        ]
    }
];
